Update Note #4 2023 12 26
- Add ModelMapper library to build.gradle: Used to simply process conversion between DTO and entities:

'implementation 'org.modelmapper:modelmapper-examples:3.1.0'

- Create config package

- Create RootConfig, specify @Configuration

- Create ModelMapper getMapper().
@Bean
private ModelMapper getMapper(){
         ModelMapper modelMapper = new ModelMapper();
         modelMapper.getConfiguration()
                 .setFieldMatchingEnabled(true)
                 .setFieldAccessLevel(org.modelmapper.config.Configuration.AccessLevel.PRIVATE)
                 .setMatchingStrategy(MatchingStrategies.STRICT);

         return modelMapper;
     }

- Add dto package and BoardDTO class

- Add service package and BoardService interface and BoardServiceImpl class.

- Implemented to inject ModelMapper (for transfer between entities and DTO) and BoardRepository (for communication using entities) into BoardServiceImpl.

Reminder:
*DTO is an object that transfers data between processes, and Entity is an object used for communication with the persistent area
//Source: https://oingdaddy.tistory.com/350 [SI Supply Depot:Tistory]//

- Implement register(BoardDTO boardDTO) in BoardService using ModelMapper in BoardServiceImple as follows. This is to change DTO into Entity using Mapper and register it in the repository:

@Service
@Log4j2
@RequiredArgsConstructor
@Transactional // This annotation tells Spring to rollback if a runtime exception occurs.
Source: https://pjh3749.tistory.com/269 [JayTech's technology blog: Tistory]
//Me(@Transactional): In addition, when multiple DB connections are expected, unexpected conflicts or conflicts between data are expected, so initialize frequently after completing the task
//Text(@Transactional): When this annotation is applied, Spring creates a "separate class" that surrounds the object. Since there may be multiple database connections in some cases, it is best to leave transaction processing as default.
//Hongpak pg.361: Binds the method in which the annotation is declared to a transaction. If you declare this annotation on a class, each method in the class will be given a separate transaction. These transaction-bound methods either execute completely from beginning to end or do not execute at all. This is because if it fails in the middle, it rolls back and returns to the initial state.

  @Override
     public Long register(BoardDTO boardDTO) {
         // DTO to Entity
         Board board = modelMapper.map(boardDTO, Board.class);
         Long bno = boardRepository.save(board).getBno();
         return bno;
     }
​

=

- Create BoardServiceTest, then create testRegister()

Registration operation processing:
- @Test
   public void testRegister(){
         log.info(boardService.getClass().getName());
// When running, the information of the "class created by wrapping BoardServiceImpl" in Spring is output instead of BoardServiceImpl.

         BoardDTO boardDTO = BoardDTO.builder()
                 .title("Sample Title...")
                 .content("Sample Content...")
                 .writer("user00")
                 .build();

         Long bno = boardService.register(boardDTO);

         log.info(bno);
     }

Inquiry task processing:
This session uses the number (bno) of a specific post.
Pretreatment:
- Add BoardDTO readOne(bno) to BoardService
- Implemented in BoardServiceImple as follows:
@Override
     public BoardDTO readOne(Long bno) {
// Board board = boardRepository.findById(bno).orElseThrow();
         Optional<Board> result = boardRepository.findById(bno);
         Board board = result.orElseThrow();
         BoardDTO boardDTO = modelMapper.map(board, BoardDTO.class);

         return boardDTO;
     }

In your test class:
// Refer to Hongpak (due to intellij defection) pg.371, 556 for utilizing assertEquals():
"import static org.junit.jupiter.api.Assertions.*;"

Me (not in the book, my own work):
@Test
     public void testSearch() {
         Long bno = 101L;
         BoardDTO boardDTO = boardService.readOne(bno);

         log.info(boardDTO.getBno().equals(bno)); //true
         assertEquals(boardDTO.getBno(), bno);
     }

Edit processing:
This session should be created to receive data to be changed from the DTO and change only the necessary parts of the existing entity object.

- Add void modify(BoardDTO boardDTO) to BoardService

- Implemented in BoardServiceImple as follows:

@Override
     public void modify(BoardDTO boardDTO) {
         Optional<Board> result = boardRepository.findById(boardDTO.getBno());
         Board board = result.orElseThrow();
         board.change(boardDTO.getTitle(), boardDTO.getContent());
         boardRepository.save(board); // If repo.save() is performed without the duplicate check process through findById() above, the relevant bno will be newly created if it does not exist in the DB, and there is no meaning in modifying it.
     }

in the test class:
@Test
     public void testModify() {

         BoardDTO boardDTO = BoardDTO.builder()
                 .bno(101L)
                 .title("Updated....101")
                 .content("Updated content 101...")
                 .build();

         boardService.modify(boardDTO);
     }

Delete operation processing:
This session only requires bno, like inquiry.
Hongpak pg.387, 581

H2 settings:
Hongpak pg.253 "spring.datasource.generate-unique-name=false",

spring.datasource.generate-unique-name=false
spring.datasource.url=jdbc:h2:mem:testdb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=password
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
https://www.baeldung.com/spring-boot-h2-database

test:
@Test
     @Transactional
     public void remove() {
         BoardDTO boardDTO = BoardDTO.builder()
                 .title("remove Title...")
                 .content("remove Content...")
                 .writer("user01")
                 .build();

         Long bno = boardService.register(boardDTO);
         boardService.remove(bno);
     }

=

- Create PageRequestDTO
PageRequestDTO specifies search type and keyword in addition to paging-related information (page/size).

- Specify @Builder.Default at the top of the “page” field of PageRequestDTO.
When creating an instance through the builder pattern, if you want to initialize a specific field to a specific value, you can use @Builder.Default.
Source: ttps://velog.io/@hsbang_thom/Lombok-Builder.Default

- Addition of getTypes(): Since the current search conditions are processed as String[] in BoardRepository, a function that returns the string applied to the "type" field as an array is needed.

- Add getPageable(String...props): It is convenient to have a function that returns the Pageable type used for paging processing, so implement it as a method as follows:
PageRequest.of(int page, int size, Sort sort) //Page number, number of data per page, sort direction

- getLink(): Configure search conditions and paging conditions as strings.

- Create PageResponseDTO

PageResponseDTO is responsible for processing the list of DTOs and start/end pages on the screen.

-Add:
@Builder(builderMethodName = "withAll")
    public PageResponseDTO(PageRequestDTO pageRequestDTO, List<E> dtoList, int total)

Among the Builder properties, ‘builderMethodName’ is used as Builder() as the default method name, allowing it to be named with a different name.
The use of this property is that in the case of an inheritance relationship, a conflict may occur because the name of the parent Builder and the child Builder are the same, so it is thought to be good to use it when you want to specify names for each.
https://adjh54.tistory.com/96

this.end = (int)(Math.ceil(this.page/10.0))*10;
// To make sure of the last page, which is a kind of practical skill, we decided to discard the decimal point through ceil.
The final number inferred is +1 of the leading digit of the current number (page), and the following digits are filled with 0. For example, when it is 21, it becomes 2.1 through (this.page/10.0), and in the ceil processing process, there is a digit greater than 1 after the decimal point, so it is rounded up and becomes +1.0. That is, it is 3.0. Afterwards, add *10 to make the final page 30. If the current page is 32, the final page is 40. Even if it is 35, it goes through 35/10 and when it is 3.5, it is still rounded to 40.
ex) this.page=15, the screen shows 11..."15"...20. Here, 11(start) is "this.start = this.end - 9" in the code, so end-9 = 20-9=11.

int last = (int)(Math.ceil((total/(double)size)));
// The last page number from which the number of data was calculated. Set the items to be printed per page by dividing the data (item) size by the total page size.
// How much data size is allowed per page. When rounding off, decimal points are discarded because calculations are made with integers.

//Summary: Math.ceil() raises if there is a number greater than 1 after the decimal point. When dividing between integers, the decimal point disappears.
Source: https://luanaeun.tistory.com/208

this.end = end > last ? last:end;
// 1. (ref. pg.483) For example, when (item qt.)total=101 and (number of items per page)size=10, int last = (int)(Math.ceil((total/( By double)size)));, the bottom highest idx# is 11.
However, if (current page) this.page is 11, end is 20 by this.end = (int)(Math.ceil(this.page/10.0))*10, which is the condition of "item qt." per page. 9 unnecessary lower idxs that far exceed the limit are created.
In other words, this is the state of end > last, and in this case, it is reasonable to adopt last that does not accommodate the 9 wasted idx.
2. If this.page=17 then end=20. If somehow item qt. fitted last=21, thus end(20)<last(21). However, the highest idx limit shown on the screen at the bottom is 10 units, so if it exceeds 20, it should not be displayed as 11...17..."21". Thus, it is reasonable for the last bottom idx to follow end=20.
3. If end==last, since both are the same without change, refer to the default variable, end.

this.prev = this.start > 1;
// this.prev valid once this.start > 1

this.next = total > this.end * this.size;
// total = this.end = max, this.size = max

- Adding "Querydsl": Although it is a framework that can dynamically generate HQL (Hibernate Query Language) used by the Hibernate framework, an implementation of JPA, it supports JPA. Because Querydsl uses Java code, you can write the query you want while maintaining type stability.
In order to use Querydsl, a Q domain is required. The Q domain is a class that is created as a separate code to use an existing entity class in Querydsl through the settings of Querydsl.

To use Querydsl, add the following to the top of build.gradle.
buildscript {
     ext {
         queryDslVersion = "5.0.0"
     }
}
The buildscript specifies the version of Querydsl with settings that Gradle uses when executing a specific task. (javax modified to jakarta)

Add Querydsl-related libraries to the dependencies section of build.gradle.

annotationProcessor(
             "jakarta.persistence:jakarta.persistence-api",
             "jakarta.annotation:jakarta.annotation-api",
             "com.querydsl:querydsl-apt:${queryDslVersion}:jakarta"
     )

Finally, specify sourceSets at the end of build.gradle.

sourceSets {
     main{
         java{
             srcDirs = ["$projectDir/src/main/java", "$projectDir/build/generated"]
         }
     }
}

The following is the procedure to check the settings of Querydsld.

Afterwards, run build->clean in the Gradle tab on the right (deletes the current build folder itself), then run other->compileJava. If you run this, a new build folder will be created and you can create and use QBoard.class.

When running compileJava
  When the error "java.lang.NoClassDefFoundError: javax/persistence/Entity" occurs, write build.gradle as follows:

1. Add annotationProcessor to gradle:

implementation("com.querydsl:querydsl-jpa:5.0.0") already
annotationProcessor("com.querydsl:querydsl-apt:5.0.0:jpa") already
// Check the presence of the two lines below, add if not present
annotationProcessor("jakarta.persistence:jakarta.persistence-api")
annotationProcessor("jakarta.annotation:jakarta.annotation-api")

If this doesn't work, you have to do method 2.

2. Change tag at the end of querydsl dependency

// add :jakarta at the end
implementation("com.querydsl:querydsl-jpa:5.0.0:jakarta")
// Modify :jpa to :jakarta at the end
annotationProcessor("com.querydsl:querydsl-apt:5.0.0:jakarta")
annotationProcessor("jakarta.persistence:jakarta.persistence-api")
annotationProcessor("jakarta.annotation:jakarta.annotation-api")
Solved here.

Source: https://l4279625.tistory.com/146

=

The following is the procedure for linking Repository and Querydsl:

- Add search package to repository, Add BoardSearch interface
- Added BoardSearchImpl. At this time, specify a parent class called QuerydslRepositorySupport and implement the interface.

Create constructor with Alt+insert.
public BoardSearchImpl(Class<?> domainClass) {
         super(domainClass);
     }

If you do not modify it as shown below, the error message "Attempt to recreate a file for type com.heeju.bootmvc.domain.QBaseEntity" will be displayed.

- public BoardSearchImpl(){ super(Board.class); }

- Add search1() to BoardSearchImpl

- Lastly, additionally specify the BoardSearch interface in the declaration part of BoardRepository as follows:
@Repository
public interface BoardRepository extends JpaRepository<Board, Long>, BoardSearch {

     @Query(value = "select now()", nativeQuery = true)
     String getTime();

}

=Creating and testing queries using the Q domain=
The purpose of Querydsl is to create and execute JPQL queries using ‘code’ based on ‘type’. At this time, instead of creating code, use a class whose class is the Q domain. Q domain is used in the created BoardSearchImpl.

- search1() modified

// JPQLQuery allows you to create JPQL written with @Query through code. Through this, where, group by, or join processing is possible. JPQLQuery can be executed using a function called fetch(), and a count query can be executed using fetchCount().

- Testing by adding testSearch1() to BoardRepositoryTests class

*Attempt to recreate a file for type error:
"This error occurs because a Q Object needs to be created, but a folder or object has already been created. This occurs when you try to create a new file, but the file exists and the file cannot be overwritten."
Source: https://melonicedlatte.com/2023/02/06/225400.html

"It is trying to generate the Querydsl classes but since those classes are already there, the test is throwing exception."
Source: https://intellij-support.jetbrains.com/hc/en-us/community/posts/360004309380-Error-java-Attempt-to-recreate-a-file-for-type-QueryDsl-classes-

Since one of the domains Board.class and QBoard already exists/occupies the build, there is a conflict, so tests that can be performed while using QBoard without conflict are as follows.

Solution>>>
Related to main text pg453:
Resolving java: Attempt to recreate a file for type error
jwkwon0817·September 3, 2023
Web Back-end

"Let me start with the conclusion. To resolve this error, simply delete the folder created when you run compileQuerydsl of gradle tasks. (Resolved by gradle tab on the right->build->clean)

"Rather than deleting and executing compileQuerydsl again, you can succeed by simply running the test in the deleted state even if an error appears in the IDE."

Me: gradle tab on the right->
1. build->clean (build folder on the left bar is deleted),
2. other->comilejava,
3. build->clean again.
If you do this, the reference to the build folder of the QBoard object disappears and turns red, but in fact, the essential files remain in the cache/registry, so it is observed that the original color returns during test operation.

This confirms that the three-stage process also works on regular servers. If you only get to step 2, the result is the same on a regular server.

Source: https://velog.io/@jwkwon0817/querydsl-recreate-failed

FYI @Override
     In this.getQuerydsl().applyPagination(pageable, query); inside public Page<Board> search1(Pageable pageable) {}
// query is the filtering method, pageble is the number of pages and sorting, etc.

**Diagnosis and Conclusion: Since the cause is a conflict between the two entities QBoard and Board, if there is already one build package in the left sidebar when the server is running, the conflict will inevitably occur. If QBoard has already been preempted in one run, a conflict will occur when the board runs when the server is restarted. In this case, it must be cleaned and updated again.

=Search conditions and list processing with Querydsl=
If there are various search conditions in the post, you can create and execute the desired JPQL using Querydsl. In the case of search, it is assumed that it is performed through a combination of 'title (t), content (c), and author (w)' and is configured to operate together with paging processing.

BooleanBuilder
For example, if a specific keyword exists in 'title or content' and you are looking for data where bno is greater than 0, write it in SQL as follows.
select * from board where (title like concat('%', '1', '%') or
content like concat('%','1','%')) order by bno desc;

When and and or are mixed in the where condition, the priorities of the operators are different, so it is better to group the or condition with '()' to create a single unit. If you need '()' when using Querydsl, you can use BooleanBuilder to write it as follows.

BooleanBuilder booleanBuilder = new BooleanBuilder(); // (
         booleanBuilder.or(board.title.contains("11")); // title like...
         booleanBuilder.or(board.content.contains("11")); //content like...

- Add testSearchAll() to BoardRepositoryTest

~~
How to change List<Entity>/Page<Entity> to List<DTO>:
List<BoardDTO> dtoList = result.getContent().stream()
                 .map(board-> modelMapper.map(board, BoardDTO.class))
                 .collect(Collectors.toList());

~~